### ISSUE TITLE
Need help to run demo project

### ISSUE THREAD

**Issue by arunsekaran02** [zoom/zoom-sdk-windows#1]
![screenshot 3](https://cloud.githubusercontent.com/assets/23396342/23849073/11af3e60-0800-11e7-86cc-54e42454aba5.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/23396342/23849081/165b1aba-0800-11e7-9f0c-95962a0667c9.png)

i have changed property as per following link and also attached my screens ...
https://zoom.us/developer/overview/getting-started-with-windows-rtc-stack

i got response like this... please help me to fix this....
![screenshot 1](https://cloud.githubusercontent.com/assets/23396342/23849083/19e4c3fc-0800-11e7-9781-d35eb3a7c9e5.png)

**Comment by datsliao** [comment]
please wait for new release,we already have fixed this issue. zoom will release new windows sdk within this week.

**Comment by datsliao** [comment]
@arunsekaran02 
you can download the new version sdk binary, to try this again.

**Comment by zainulabidin302** [comment]
![image](https://user-images.githubusercontent.com/7473349/28021641-085d941a-65a2-11e7-8c35-cdf16718cc00.png)
I have just downloaded the app (after your comment), followed the instructions to setup the directories in VS2015 Community and got the same errors (see the image attached). Can you explain this issue?

**Comment by zainulabidin302** [comment]
![image](https://user-images.githubusercontent.com/7473349/28022297-360157d8-65a4-11e7-8289-af7b97a82f35.png)
Found the solution, changing the development from debug to release did fix the problem. Can anyone explain why is this?

**Comment by datsliao** [comment]
yes, now only "release" mode worked. we don't provide debug version sdk binary. thanks.
