### ISSUE TITLE
C# Wrapper - onAuthenticationReturn not being called

### ISSUE THREAD

**Issue by cleytonb** [zoom/zoom-sdk-windows#2]
Hi,

Since I couldn't find a C# example/wrapper, I decided to write my own. I've tested the sdk_demo project and everything worked fine, so, I made a copy of the AuthServiceMgr cpp and h to another project (removing the DemoUI references), referenced the libs, includes, etc and copied all the runtime dll's.

The calls to InitSDK, CreateAuthService, SetEvent and SDKAuth works as it should. The modifications I made were simple:

[AuthServiceMgr.h]
```
class CAuthServiceMgr : public ZOOM_SDK_NAMESPACE::IAuthServiceEvent
{
public:
        //
private:
        //
};

namespace ZoomSdkNet {
	public ref class ManagedTest {
	public:
		ManagedTest();
		bool Init();
		bool SDKAuth();
	private:
		CAuthServiceMgr* mgr;
	};
}
```

[AuthServiceMgr.cpp]
```
#include "Stdafx.h"

#include "AuthServiceMgr.h"
#include "zoom_sdk_def.h"


CAuthServiceMgr::CAuthServiceMgr()
{
	m_bInited = false;
	m_bLogined = false;
}

CAuthServiceMgr::~CAuthServiceMgr()
{
	m_bInited = false;
	m_bLogined = false;
}

// 

ZoomSdkNet::ManagedTest::ManagedTest() {
	mgr = new CAuthServiceMgr();
}

bool ZoomSdkNet::ManagedTest::Init() {
	ZOOMSDK::InitParam param;
	param.strWebDomain = _T("https://zoom.us/");
	return mgr->Init(param);
}

bool ZoomSdkNet::ManagedTest::SDKAuth() {
	ZOOMSDK::AuthParam param;
	param.appKey = _T("B4mtyM2X1icObcU9SSlF0H8ECQpuNpxND2hS");
	param.appSecret = _T("M6yiWcGh8vUjjLxnvO8rBQt63qPD8vTjaLw2");
	return mgr->SDKAuth(param);
}
```

That way I can call the ManagedTest from C#. The problem is that the onAuthenticationReturn never gets called. I tested again the sdk_demo project and it works. I think I'm missing some project configuration.

Do you have any clues?

**Comment by datsliao** [comment]
you need to call sdk api in main thread and your app should have a message loop. thanks.

**Comment by cleytonb** [comment]
I was trying to execute from a console application. Creating a WPF Application seems to be working fine.
Thank you!

**Comment by demoishan** [comment]
Hey cleytonb can you give demo of your WPF application.???/my mail id is ishan1112@gmail.com

**Comment by demoishan** [comment]
Hey @cleytonb can you give demo of your WPF application.???my mail id is ishan1112@gmail.com
