### ISSUE TITLE
 The process does not respond。

### ISSUE THREAD

**Issue by mengxuxin** [zoom/zoom-sdk-windows#4]
when i run Demo, i start/join a meeting. choose a sharing, and  Start Annotation. when i end/leave meeting the process doesn't respond.
![image](https://user-images.githubusercontent.com/8519362/28555293-875e6c2c-7131-11e7-8654-8a9d983f1b13.png)
![image](https://user-images.githubusercontent.com/8519362/28555303-95989542-7131-11e7-99d4-e96237cee33c.png)
the process is still on this window, don't respond

**Comment by mengxuxin** [comment]
i use api user to start/join

**Comment by datsliao** [comment]
this is a known issue caused by windows system module.
please update the drivers for the graphics card to the latest version, and retry this case again.
thanks.

**Comment by mengxuxin** [comment]
I want to know why the zoom.exe don't have this issue

**Comment by datsliao** [comment]
different architecture between zoom windows sdk and zoom client. thanks.

**Comment by mengxuxin** [comment]
how can i avoid this issue when i use this sdk,
how can i see other known issue? thanks.

**Comment by mengxuxin** [comment]
Is there a plan to solve this problem?

**Comment by mengxuxin** [comment]
This problem in the win10 on the probability of reproduction is relatively high. thanks

**Comment by datsliao** [comment]
if ok for u, save the full dump when the issue happened. and post the download link of full dump here. thanks

**Comment by mengxuxin** [comment]
there are the dump files; thanks

[logs.zip](https://github.com/zoom/zoom-sdk-windows/files/1186226/logs.zip)

**Comment by datsliao** [comment]
from your attached, i can't found any app stuck dump. please check it again. 
BTW, please use the latest sdk(4.0.35674.0608) to reproduce this issue. 
and, please save the full dump when the issue happened, not sdk crash handler's dumps in our log folder.
thanks.

**Comment by mengxuxin** [comment]
when the issue happened ,i create a dmp file, but it's too big to not post here. i send a mail to your datsliao@gmail.com. thanks

**Comment by datsliao** [comment]
thanks for your help. next release we will fix this issue if everything goes well.  thanks.

**Comment by mengxuxin** [comment]
Looking forward to your settlement thanks.

**Comment by mengxuxin** [comment]
How to remove "powered by zoom". thanks

**Comment by datsliao** [comment]
this is paid feature. please contact our sales on our web site.

**Comment by datsliao** [comment]
@mengxuxin the latest package fix the deadlock issue. please have a try. thanks
